### ISSUE TITLE
Implement node focus

### ISSUE THREAD

**Issue by benedyktdryl** [benedyktdryl/mindmaps#14]
# TODO

- [ ] implement focus store
- [ ] implement highlighted node custom styling
- [ ] implement delegate for focusing node on click
- [ ] reuse workspace page as a module
